#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
#rm -rf 0.orig/lagrangian
cleanCase
rm -rf FTResult/printFrontsForAllTimesPLT
rm -rf FTResult/BubblePositionsPLT
rm -rf FTResult/BubbleVelocityAndAccelarationPLT
rm -rf FTResult/BubbleSphericityPLT
rm -rf FTResult/BubbleDragCoefsPLT
rm -rf FTResult/BubbleLiftCoefsPLT
rm -rf FTResult/BubbleDiameterComponentsPLT

rm -rf FTResult/*.plt
rm -rf *.plt
rm -rf bubbleData
rm -rf 0 

# ----------------------------------------------------------------- end-of-file
