#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

echo $application

m4 -P expansion3D.m4 > system/blockMeshDict

cp -r 0.org 0

runApplication blockMesh

runApplication checkMesh

runApplication renumberMesh -overwrite

runApplication $application
