#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

echo $application

m4 -P box.m4 > system/blockMeshDict

cp -r 0.org 0

runApplication blockMesh

runApplication checkMesh
#runApplication $application > log 

runApplication renumberMesh -overwrite

runApplication decomposePar

mv log.checkMesh log.checkMesh0 
runParallel checkMesh

runParallel $application

runApplication reconstructParMesh
runApplication reconstructPar

runApplication postProcess -func sampleDict -latestTime

# ----------------------------------------------------------------- end-of-file
