#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

echo $application

cp -r 0.org 0

m4 -P box.m4 > system/blockMeshDict

runApplication blockMesh
runApplication checkMesh
runApplication setFields

runApplication renumberMesh -overwrite

runApplication decomposePar

mv log.checkMesh log.checkMesh0 
runParallel checkMesh

#runApplication mpirun -np 4 renumberMesh -overwrite -parallel
#mv log.mpirun log.renumberMesh

runParallel $application

runApplication reconstructParMesh
runApplication reconstructPar

./plots.sh
