#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf *.png
#rm -rf 0/alpha.water
rm -rf 0 
rm -rf *.dat
rm -rf constant/dynamicMeshDict

rm -rf system/fvScheme

# ----------------------------------------------------------------- end-of-file
