#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

echo $application

m4 -P expansion3D.m4 > system/blockMeshDict

cp -r 0.org 0

runApplication blockMesh
runApplication setFields

runApplication checkMesh

runApplication renumberMesh -overwrite

runApplication decomposePar

mv log.checkMesh log.checkMesh0 
runParallel checkMesh

#runApplication mpirun -np 4 renumberMesh -overwrite -parallel
#mv log.mpirun log.renumberMesh

runParallel $application

runApplication reconstructParMesh
runApplication reconstructPar
